# Generated by Django 4.1.7 on 2023-05-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_habit"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="frequency",
            field=models.CharField(
                choices=[("D", "Daily"), ("W", "Weekly"), ("M", "Mounthly")],
                default=[("D", "Daily")],
                max_length=1,
            ),
        ),
    ]
